import { expect, test } from "@playwright/test";
import net from "node:net";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

test.describe.configure({ mode: "serial" });

test("advisory landing, real client and mandate workflow, keyboard dialog", async ({ page }) => {
  const failures: string[] = [];
  page.on("pageerror", error => failures.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Your work, in focus." })).toBeVisible();
  await expect(page.locator(".globe-overlay")).toHaveCount(0);
  await page.getByRole("button", { name: "Add your first client" }).click();
  const dialog = page.getByRole("dialog", { name: "New client" });
  await expect(dialog).toBeVisible();
  await page.keyboard.press("Shift+Tab");
  await expect(dialog.locator(":focus")).toHaveCount(1);
  await dialog.getByLabel("Client or company name").fill("Clear browser verification");
  await dialog.getByRole("button", { name: "Save client" }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole("button", { name: "New deal", exact: true }).first().click();
  const deal = page.getByRole("dialog", { name: "New deal" });
  await deal.getByRole("combobox", { name: "Client *", exact: true }).selectOption({ label: "Clear browser verification" });
  await deal.getByLabel("Deal name").fill("Advisory workflow verification");
  await deal.getByLabel("Deal owner").fill("Verification operator");
  await deal.getByLabel("Source / basis").fill("Operator-created acceptance record in an isolated database; no client or market facts claimed.");
  await deal.getByLabel("Next action").fill("Verify client handoff");
  await deal.getByRole("button", { name: "Save deal" }).click();
  await expect(page.getByRole("button", { name: "Advisory workflow verification" })).toBeVisible();
  await page.reload();
  await expect(page.getByText("Verify client handoff", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Advisory workflow verification" }).click();
  await page.getByRole("dialog").getByRole("combobox", { name: "Stage", exact: true }).selectOption("mandated");
  await page.getByRole("button", { name: "Save deal" }).click();
  await expect(page.locator("tbody").getByText("Mandated", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "History", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("prospect → mandated");
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Tasks & diligence" }).click();
  await page.getByRole("button", { name: "New task" }).click();
  const task = page.getByRole("dialog");
  await task.getByRole("combobox", { name: "Client *", exact: true }).selectOption({ label: "Clear browser verification" });
  await task.getByLabel("Task title").fill("Verify review workflow");
  await task.getByLabel("Task owner").fill("Verification operator");
  await task.getByLabel("Source / basis").fill("Actual isolated browser acceptance run.");
  await task.getByRole("button", { name: "Save task" }).click();
  await page.getByRole("button", { name: "Complete Verify review workflow" }).click();
  await expect(page.getByText("Completed", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Relationships", exact: true }).click();
  await page.getByRole("button", { name: "New contact" }).click();
  const contact = page.getByRole("dialog");
  await contact.getByRole("combobox", { name: "Client *", exact: true }).selectOption({ label: "Clear browser verification" });
  await contact.getByLabel("Contact name").fill("Acceptance operator");
  await contact.getByLabel("Relationship owner").fill("Verification operator");
  await contact.getByLabel("Source / basis").fill("Actual isolated acceptance run; not a customer contact.");
  await contact.getByRole("button", { name: "Save contact" }).click();
  await expect(page.getByRole("heading", { name: "Acceptance operator" })).toBeVisible();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export", exact: true }).click();
  expect((await download).suggestedFilename()).toContain("clear-advisory");
  await page.getByRole("button", { name: "Deal pipeline", exact: true }).click();
  await page.screenshot({ path: "test-results/advisory-desktop.png", fullPage: true });
  expect(failures).toEqual([]);
});

test("arithmetic-only DCF and comparable models save, reload, and preserve versions through real API", async ({ page }) => {
  await page.goto("/valuation");
  const source = "Deterministic arithmetic acceptance inputs only, not a company valuation or market evidence.";
  await page.getByLabel("Valuation date").fill("2026-01-01");
  await page.getByLabel("Sources and assumption basis").fill(source);
  await page.getByLabel("Year 1 FCFF").fill("100");
  await page.getByLabel("WACC (%)").fill("10");
  await page.getByLabel("Terminal growth (%)").fill("0");
  for (const name of ["cash", "debt", "other_claims", "non_operating_assets"]) await page.locator(`input[name="${name}"]`).fill("0");
  await page.getByRole("button", { name: "Calculate valuation", exact: true }).click();
  await expect(page.locator(".bank-value").first()).toHaveText("$1,000.00");
  await page.getByLabel("Model name").fill("DCF arithmetic snapshot");
  await page.getByLabel("Prepared by").fill("Acceptance operator");
  await page.getByRole("combobox", { name: "Model client *", exact: true }).selectOption({ label: "Clear browser verification" });
  await page.getByRole("button", { name: "Save model version" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Valuation saved" })).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "Load assumptions" }).click();
  await expect(page.getByLabel("Year 1 FCFF")).toHaveValue("100");
  await page.getByRole("button", { name: "Calculate valuation", exact: true }).click();
  await page.getByLabel("Model name").fill("DCF arithmetic revision");
  await page.getByLabel("Prepared by").fill("Acceptance operator");
  await page.getByRole("button", { name: "Save model version" }).click();
  await expect(page.getByRole("cell", { name: "Revised snapshot", exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Comparable companies", exact: true }).click();
  await page.getByLabel("Observation date").fill("2026-01-01");
  await page.locator('textarea[name="source_note"]').fill(source);
  for (const name of ["cash", "debt", "other_claims", "non_operating_assets"]) await page.locator(`input[name="${name}"]`).fill("0");
  await page.getByLabel("Target revenue").fill("200");
  await page.getByLabel("Target EBITDA").fill("20");
  await page.getByLabel("Peer 1 name").fill("Arithmetic acceptance peer");
  await page.getByLabel("Peer 1 enterprise value").fill("1000");
  await page.getByLabel("Peer 1 revenue").fill("100");
  await page.getByLabel("Peer 1 ebitda").fill("10");
  await page.getByLabel("Peer 1 source note").fill(source);
  await page.getByRole("button", { name: "Calculate comparables", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Peer multiples & implied value" })).toBeVisible();
  await expect(page.getByRole("cell", { name: "$2,000.00", exact: true }).first()).toBeVisible();
  await page.getByLabel("Model name").fill("Comparable arithmetic snapshot");
  await page.getByLabel("Prepared by").fill("Acceptance operator");
  await page.getByRole("combobox", { name: "Model client *", exact: true }).selectOption({ label: "Clear browser verification" });
  await page.getByRole("button", { name: "Save model version" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Valuation saved" })).toBeVisible();
});

test("mobile layout, World menu and valuation validation", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/valuation");
  await expect(page.getByRole("heading", { name: "Understand the value drivers." })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByText("Workspace", { exact: true }).click();
  await expect(page.getByRole("button", { name: "Open World", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Calculate valuation" }).click();
  await expect(page.locator("input:invalid").first()).toBeVisible();
  await page.screenshot({ path: "test-results/advisory-mobile.png", fullPage: true });
});

test("client profile loads independently and hidden pattern analysis stays idle", async ({ page, request }) => {
  const api = "http://127.0.0.1:18080";
  const headers = { "X-API-Key": "isolated-browser-verification" };
  const indexResponse = await request.get(`${api}/api/clients`, { headers });
  expect(indexResponse.ok()).toBeTruthy();
  const client = (await indexResponse.json()).clients.find((row: { name: string }) => row.name === "Clear browser verification");
  expect(client).toBeTruthy();
  const accountResponse = await request.post(`${api}/api/clients/${client.client_id}/accounts`, { headers, data: { account_name: "Isolated loading verification", account_type: "Taxable", holdings: {} } });
  expect(accountResponse.ok(), await accountResponse.text()).toBeTruthy();
  const account = (await accountResponse.json()).account;
  const profilePath = `/api/clients/${client.client_id}`;
  const observed: string[] = [];
  const failures: string[] = [];
  page.on("request", req => observed.push(new URL(req.url()).pathname));
  page.on("pageerror", error => failures.push(error.message));
  await page.goto(`/clients?client=${encodeURIComponent(client.client_id)}`);
  await expect(page.getByRole("button", { name: /Client Profile Clear browser verification/ })).toBeVisible();
  await expect(page.getByRole("button", { name: "Refresh snapshot", exact: true })).toBeEnabled();
  expect(observed.filter(url => url.endsWith("/patterns"))).toEqual([]);
  await expect(page.getByText("Return History Surface", { exact: true })).toHaveCount(0);
  const profileLoads = observed.filter(url => url === profilePath).length;
  const accountDashboard = page.waitForResponse(response => new URL(response.url()).pathname === `${profilePath}/accounts/${account.account_id}/dashboard`);
  await page.getByLabel("Portfolio scope").selectOption(account.account_id);
  await accountDashboard;
  await expect(page.getByRole("button", { name: "Refresh snapshot", exact: true })).toBeEnabled();
  expect(observed.filter(url => url === profilePath)).toHaveLength(profileLoads);
  expect(observed.filter(url => url.endsWith("/patterns"))).toEqual([]);
  const patternRequest = page.waitForRequest(req => new URL(req.url()).pathname.endsWith("/patterns"));
  await page.getByRole("button", { name: /Pattern Analysis Load on demand/ }).click();
  await patternRequest;
  await expect(page.getByText("Realtime valuations active.", { exact: true })).toHaveCount(0);
  expect(failures).toEqual([]);
});

function isListening(port: number): Promise<boolean> {
  return new Promise(resolve => { const socket = net.createConnection({ host: "127.0.0.1", port }); socket.setTimeout(500); socket.once("connect", () => { socket.destroy(); resolve(true); }); socket.once("error", () => resolve(false)); socket.once("timeout", () => { socket.destroy(); resolve(false); }); });
}

test("close app confirms and stops both real isolated servers", async ({ page }) => {
  const runtimeRoot = path.resolve("../test_runtime");
  const runtimes = fs.readdirSync(runtimeRoot).filter(name => name.startsWith(`advisory-browser-${process.env.CLEAR_ACCEPTANCE_RUN_ID}-`));
  expect(runtimes).toHaveLength(1);
  const controlDir = path.join(runtimeRoot, runtimes[0], "data/runtime");
  const controlName = fs.readdirSync(controlDir).find(name => name.startsWith("stack-") && name.endsWith(".json"))!;
  const controlPath = path.join(controlDir, controlName);
  const ownership = JSON.parse(fs.readFileSync(controlPath, "utf8"));
  await page.goto("/");
  await page.getByRole("button", { name: "Close app", exact: true }).click();
  await page.getByRole("button", { name: "Keep working" }).click();
  await expect(page.getByRole("heading", { name: "Your work, in focus." })).toBeVisible();
  await page.getByRole("button", { name: "Close app", exact: true }).click();
  const shutdownStarted = Date.now();
  await page.getByRole("button", { name: "Close Clear safely" }).click();
  await expect(page.getByRole("heading", { name: "Clear is shutting down." })).toBeVisible();
  await expect.poll(async () => [await isListening(18080), await isListening(15173)], { timeout: 25000 }).toEqual([false, false]);
  await expect.poll(() => JSON.parse(execFileSync("python", ["-c", "import json,sys,psutil; records=json.loads(sys.argv[1]); identities=[identity for record in records.values() for identity in [record]+record.get('children',[])]; running={p.pid:p.create_time() for p in psutil.process_iter()}; print(json.dumps([i['pid'] for i in identities if running.get(i['pid'])==i['created']]))", JSON.stringify(ownership.processes)], { encoding: "utf8" })), { timeout: 10000 }).toEqual([]);
  expect(JSON.parse(fs.readFileSync(controlPath, "utf8")).shutdown_result).toBe("stopped");
  console.log(`Idle stack shutdown verified in ${Date.now() - shutdownStarted} ms`);
});
