import { useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowUpRight, BriefcaseBusiness, CheckCircle2, Download, Plus, RefreshCw, Search } from "lucide-react";
import { apiGet, apiPatch, useApi } from "../lib/api";
import { calendarDate, dealTypes, downloadJson, money, stages, taskStatuses, type Workspace, type BankRecord } from "../lib/banking";
import { RecordForm, type FormKind } from "../components/banking/RecordForm";
import { Modal } from "../components/ui/Modal";

const empty: Workspace = { clients: [], deals: [], contacts: [], tasks: [], summary: { active_deals: 0, open_tasks: 0, overdue_tasks: 0, by_currency: [] }, meta: { timestamp: 0, warnings: [] } };
type Activity = { id: string; created_at: string; action: string; changes: Record<string, { before: unknown; after: unknown }> };
export default function Advisory() {
  const api = useApi<Workspace>("/api/banking/workspace", { interval: 60000 });
  const data = api.data || empty;
  const [params, setParams] = useSearchParams();
  const tab = ["pipeline", "relationships", "tasks"].includes(params.get("view") || "") ? params.get("view")! : "pipeline";
  const [query, setQuery] = useState("");
  const [clientFilter, setClientFilter] = useState("");
  const [stageFilter, setStageFilter] = useState("");
  const [form, setForm] = useState<{ kind: FormKind; record?: BankRecord } | null>(null);
  const [notice, setNotice] = useState("");
  const [actionError, setActionError] = useState("");
  const [busy, setBusy] = useState(false);
  const [activity, setActivity] = useState<{ name: string; events: Activity[] } | null>(null);
  const names = useMemo(() => Object.fromEntries(data.clients.map(client => [client.client_id, client.name])), [data.clients]);
  const needle = query.trim().toLowerCase();
  const matches = (row: BankRecord, text: string) => (!clientFilter || row.client_id === clientFilter) && `${text} ${names[row.client_id] || ""}`.toLowerCase().includes(needle);
  const deals = data.deals.filter(deal => matches(deal, `${deal.name} ${deal.owner}`) && (!stageFilter || deal.stage === stageFilter));
  const contacts = data.contacts.filter(contact => matches(contact, `${contact.name} ${contact.email} ${contact.owner}`));
  const tasks = data.tasks.filter(task => matches(task, `${task.title} ${task.owner}`)).sort((a, b) => Number(a.status === "completed") - Number(b.status === "completed") || String(a.due_date || "9999").localeCompare(String(b.due_date || "9999")));
  const today = new Date().toISOString().slice(0, 10);
  const disabled = !api.data || Boolean(api.error) || busy;
  function saved() { setNotice("Saved to your workspace."); api.refresh(); }
  async function complete(task: BankRecord) {
    setBusy(true); setActionError("");
    try { await apiPatch(`/api/banking/tasks/${task.id}`, { expected_revision: task.revision, status: task.status === "completed" ? "open" : "completed" }); saved(); }
    catch (reason) { setActionError(reason instanceof Error ? reason.message : "Unable to update task."); }
    finally { setBusy(false); }
  }
  async function exportWorkspace() {
    setBusy(true); setActionError("");
    try { downloadJson(await apiGet("/api/banking/export"), `clear-advisory-${today}.json`); setNotice("Workspace export downloaded with source notes and methodology."); }
    catch (reason) { setActionError(reason instanceof Error ? reason.message : "Export failed."); }
    finally { setBusy(false); }
  }
  async function showActivity(deal: BankRecord) {
    try { const response = await apiGet<{ activities: Activity[] }>(`/api/banking/deals/${deal.id}/activity`); setActivity({ name: String(deal.name), events: response.activities }); }
    catch (reason) { setActionError(reason instanceof Error ? reason.message : "Activity could not be loaded."); }
  }
  return <div className="bank-workspace">
    <header className="bank-heading"><div><p className="bank-eyebrow">ADVISORY WORKSPACE</p><h1>Your work, in focus.</h1><p className="bank-muted">Add a client, open a deal, then keep the next action on the task list. Click a deal or contact name to edit it.</p></div><div className="bank-actions"><button className="bank-button" onClick={exportWorkspace} disabled={disabled}><Download size={16} /> Export</button><button className="bank-button" disabled={disabled} onClick={() => setForm({ kind: "client" })}><Plus size={17} /> New client</button><button className="bank-button bank-primary" disabled={disabled || !data.clients.length} onClick={() => setForm({ kind: "deal" })}><Plus size={17} /> New deal</button></div></header>
    {(api.error || actionError) && <div role="alert" className="bank-error">{api.error || actionError} <button className="bank-button" onClick={() => { setActionError(""); api.refresh(); }}>Reload workspace</button>{api.error && api.data && <p>Last loaded records are shown. Changes are disabled until the connection is restored.</p>}</div>}
    <p role="status" className="bank-status">{notice || (api.loading ? "Loading workspace…" : api.data ? `Updated ${new Date(data.meta.timestamp * 1000).toLocaleString()}` : "")}</p>
    <section className="bank-stats" aria-label="Workspace summary">{[["Active mandates & opportunities", data.summary.active_deals], ["Client relationships", data.clients.length], ["Open actions", data.summary.open_tasks], ["Overdue actions · UTC", data.summary.overdue_tasks]].map(([label, value]) => <div className="bank-stat" key={label}><span>{label}</span><strong>{api.data ? value : "—"}</strong></div>)}</section>
    {api.data && !data.clients.length && <section className="bank-onboarding"><div><p className="bank-eyebrow">START WITH A RELATIONSHIP</p><h2>A clear path from client to close.</h2><p>Add a client, create an opportunity, then assign your first follow-up. Portfolio accounts can be added whenever you need them.</p></div><button className="bank-button bank-primary" onClick={() => setForm({ kind: "client" })} disabled={disabled}>Add your first client <ArrowUpRight size={16} /></button></section>}
    <section className="bank-panel"><div className="bank-panel-heading"><div className="bank-tabs" aria-label="Workspace views">{[["pipeline", "Deal pipeline"], ["relationships", "Relationships"], ["tasks", "Tasks & diligence"]].map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} aria-pressed={tab === id} onClick={() => { setParams({ view: id }); setStageFilter(""); }}>{label}</button>)}</div><button className="bank-icon-button" aria-label="Refresh workspace" onClick={api.refresh} disabled={api.loading}><RefreshCw size={17} /></button></div>
      <div className="bank-toolbar"><label className="bank-search"><Search size={17} /><input aria-label="Search workspace" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search clients, records, or owners" /></label><select aria-label="Filter by client" value={clientFilter} onChange={event => setClientFilter(event.target.value)}><option value="">All clients</option>{data.clients.map(client => <option key={client.client_id} value={client.client_id}>{client.name}</option>)}</select>{tab === "pipeline" && <select aria-label="Filter by stage" value={stageFilter} onChange={event => setStageFilter(event.target.value)}><option value="">All stages</option>{Object.entries(stages).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>}<button className="bank-button" disabled={disabled || (!data.clients.length && tab !== "relationships")} onClick={() => setForm({ kind: tab === "relationships" ? "client" : tab === "tasks" ? "task" : "deal" })}><Plus size={16} />{tab === "relationships" ? "New client" : tab === "tasks" ? "New task" : "New deal"}</button>{tab === "relationships" && <button className="bank-button" disabled={disabled || !data.clients.length} onClick={() => setForm({ kind: "contact" })}>New contact</button>}</div>
      {tab === "pipeline" && <><div className="bank-table-scroll"><table className="bank-table"><caption className="sr-only">Client-linked deal pipeline</caption><thead><tr><th scope="col">Deal / client</th><th scope="col">Stage</th><th scope="col">Transaction value</th><th scope="col">Next action</th><th scope="col">Owner / close</th><th scope="col">Actions</th></tr></thead><tbody>{deals.map(deal => <tr key={deal.id}><th scope="row"><button className="bank-text-button" onClick={() => setForm({ kind: "deal", record: deal })} disabled={disabled}>Edit {String(deal.name)}</button><Link className="bank-subline" to={`/clients?client=${encodeURIComponent(deal.client_id)}`}>{names[deal.client_id]} · open portfolio</Link><span className="bank-subline">{dealTypes[String(deal.deal_type) as keyof typeof dealTypes]}</span></th><td><span className={`bank-badge stage-${deal.stage}`}>{stages[String(deal.stage) as keyof typeof stages]}</span></td><td className="bank-number">{money(deal.expected_value, String(deal.currency))}<span className="bank-subline">{String(deal.currency)} · estimate</span></td><td className="bank-wrap">{String(deal.next_action || "Set a next action")}</td><td>{deal.owner}<span className="bank-subline">{calendarDate(deal.target_close)}</span></td><td><button className="bank-text-button" onClick={() => showActivity(deal)}>History</button></td></tr>)}</tbody></table></div>{!deals.length && <div className="bank-empty"><BriefcaseBusiness size={26} /><h3>{data.deals.length ? "No deals match these filters" : "Your next mandate starts here"}</h3><p>{data.deals.length ? "Try a different search or client." : "Record a prospect or signed mandate. Add estimates when you have a basis for them."}</p></div>}</>}
      {tab === "relationships" && <div className="bank-relationships"><div><h2>Clients</h2>{data.clients.filter(client => (!clientFilter || client.client_id === clientFilter) && client.name.toLowerCase().includes(needle)).map(client => <article className="bank-client-row" key={client.client_id}><div><h3>{client.name}</h3><p className="bank-muted">{data.deals.filter(deal => deal.client_id === client.client_id).length} deals · {data.contacts.filter(contact => contact.client_id === client.client_id).length} contacts · {client.accounts_count} investment accounts</p></div><div className="bank-actions"><button className="bank-text-button" disabled={disabled} onClick={() => { setClientFilter(client.client_id); setForm({ kind: "deal" }); }}>Add deal</button><Link className="bank-text-button" to={`/clients?client=${encodeURIComponent(client.client_id)}`}>Edit holdings <ArrowUpRight size={14} /></Link></div></article>)}{!data.clients.length && <p className="bank-muted">No client relationships yet.</p>}</div><div><h2>People & coverage</h2>{contacts.map(contact => <article className="bank-client-row" key={contact.id}><div><h3>{String(contact.name)}</h3><p className="bank-muted">{String(contact.title)} · {names[contact.client_id]}</p>{Boolean(contact.email) && <a href={`mailto:${contact.email}`} className="bank-text-button">{String(contact.email)}</a>}<p className="bank-muted">Owner: {contact.owner}</p>{Boolean(contact.notes) && <p className="bank-wrap">{String(contact.notes)}</p>}<p className="bank-muted">Source: {contact.source_note}</p></div><button className="bank-text-button" disabled={disabled} onClick={() => setForm({ kind: "contact", record: contact })}>Edit contact</button></article>)}{!contacts.length && <p className="bank-muted">Add a contact to keep relationship context with the client.</p>}</div></div>}
      {tab === "tasks" && <div className="bank-task-list">{tasks.map(task => <article className="bank-task" key={task.id}><button className="bank-icon-button" aria-label={`${task.status === "completed" ? "Reopen" : "Complete"} ${task.title}`} disabled={disabled} onClick={() => complete(task)}><CheckCircle2 size={21} className={task.status === "completed" ? "bank-complete" : ""} /></button><div><button className="bank-text-button" disabled={disabled} onClick={() => setForm({ kind: "task", record: task })}>{String(task.title)}</button><p className="bank-muted">{names[task.client_id]} · {task.owner}</p>{Boolean(task.notes) && <p className="bank-wrap">{String(task.notes)}</p>}</div><div className="bank-task-date"><span className="bank-badge">{taskStatuses[String(task.status) as keyof typeof taskStatuses]}</span><p className="bank-muted">{task.status !== "completed" && task.due_date && String(task.due_date) < today ? "Overdue · " : ""}{calendarDate(task.due_date)}</p></div></article>)}{!tasks.length && <div className="bank-empty"><CheckCircle2 size={26} /><h3>No actions to show</h3><p>Add a follow-up, diligence request, meeting, or deliverable with an owner.</p></div>}</div>}
    </section>
    {data.summary.by_currency.length > 0 && <section className="bank-panel bank-padded"><h2>Pipeline estimates by currency</h2><p className="bank-muted">Available estimates only; excludes closed, lost and on-hold deals. Weighted fees use your close probabilities and are not booked revenue.</p><div className="bank-table-scroll"><table className="bank-table"><thead><tr><th>Currency</th><th>Transaction value</th><th>Success fees</th><th>Weighted fees</th></tr></thead><tbody>{data.summary.by_currency.map(row => <tr key={row.currency}><th scope="row">{row.currency}</th><td>{money(row.pipeline_value, row.currency)}<span className="bank-subline">{row.value_coverage}/{row.deals} deals provided</span></td><td>{money(row.expected_fees, row.currency)}<span className="bank-subline">{row.fee_coverage}/{row.deals} deals provided</span></td><td>{money(row.weighted_fees, row.currency)}<span className="bank-subline">{row.weighted_coverage}/{row.deals} deals provided</span></td></tr>)}</tbody></table></div></section>}
    <div className="bank-bottom-grid">{[["VALUATION & ANALYSIS", "Make the assumptions visible.", "Build a discounted cash flow valuation, inspect the equity bridge, and test discount rate and growth assumptions.", "/valuation", "Open valuation"], ["PORTFOLIO MANAGEMENT", "The whole client relationship.", "Manage investment accounts, holdings, lots, and risk analysis alongside advisory work.", "/clients", "Open client portfolios"]].map(([eyebrow, title, copy, url, cta]) => <section className="bank-panel bank-padded" key={url}><p className="bank-eyebrow">{eyebrow}</p><h2>{title}</h2><p className="bank-muted">{copy}</p><Link className="bank-button" to={url}>{cta} <ArrowUpRight size={16} /></Link></section>)}</div>
    {form && <RecordForm key={`${form.kind}-${form.record?.id || "new"}`} {...form} workspace={data} clientId={clientFilter} onClose={() => setForm(null)} onSaved={saved} />}
    {activity && <Modal open title={`${activity.name} · change history`} description="Local application changes; these entries do not identify an authenticated individual." onClose={() => setActivity(null)}>{activity.events.map(event => <article className="bank-activity" key={event.id}><h3>{event.action} · {new Date(event.created_at).toLocaleString()}</h3><dl>{Object.entries(event.changes).map(([field, change]) => <div key={field}><dt>{field.replace(/_/g, " ")}</dt><dd>{String(change.before ?? "Not set")} → {String(change.after ?? "Not set")}</dd></div>)}</dl></article>)}</Modal>}
  </div>;
}
